version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: hr_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hr_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    container_name: hr_fastapi_app
    restart: always
    volumes:
      - ./app:/app
      - ./alembic:/alembic
      - ./alembic.ini:/alembic.ini
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: ["sh", "-c",  "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hr_network
volumes:
  postgres_data:
networks:
  hr_network:
    driver: bridge