"""add salary to employee

Revision ID: a2ef598ad9f8
Revises: ee341b1631fd
Create Date: 2026-05-20 13:09:19.033654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ef598ad9f8'
down_revision: Union[str, Sequence[str], None] = 'ee341b1631fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('salary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'salary')
    # ### end Alembic commands ###
